name: transmilenio-project
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - polars
  - pyarrow
  - geopandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - pytest
  - ruff
  - dash
  - dash-bootstrap-components
  - pandas
  - scikit-learn
  - joblib
  - numpy
  - plotly
  - gunicorn
  - pip:
    - python-dotenv
    - mkdocs
    - -e .