# =============================================================================
# TransMilenio Dashboard — Configuración Central
# Temas, idiomas, rutas de datos y constantes institucionales.
# =============================================================================

import os

# ──── Rutas de Datos ────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(BASE_DIR))
_geojson_artefactos = os.path.join(BASE_DIR, "models", "artefactos", "stations_clean.geojson")
_geojson_repo = os.path.join(PROJECT_ROOT, "data", "processed", "stations_clean.geojson")
GEOJSON_PATH = _geojson_artefactos if os.path.exists(_geojson_artefactos) else _geojson_repo

# ──── Identidad Visual Institucional ────
TM_ROJO = "#C1001F"
TM_AMARILLO = "#FFD100"
TM_TEXTO = "#333333"
TM_FONDO = "#F4F6F9"

# ──── Definición de Temas (Claro / Oscuro) ────
THEMES = {
    "light": {
        "bg_base": "#F4F6F9",
        "card_bg": "#FFFFFF",
        "text_main": "#333333",
        "text_muted": "#6C757D",
        "border": "#DEE2E6",
        "chart_box": "#F8F9FA",
        "trend_up": "text-success",
        "trend_down": "text-danger",
        "trend_warn": "text-warning",
    },
    "dark": {
        "bg_base": "#121212",
        "card_bg": "#1E1E1E",
        "text_main": "#F8F9FA",
        "text_muted": "#ADB5BD",
        "border": "#2C2C2C",
        "chart_box": "#252525",
        "trend_up": "text-success",
        "trend_down": "text-danger",
        "trend_warn": "text-warning",
    }
}

# ──── Diccionario de Traducciones (i18n) ────
LANGUAGES = {
    "es": {
        "nav_title": "TransMilenio | Monitoreo y Análisis Operativo",
        "theme_light": "Claro",
        "theme_dark": "Oscuro",
        "kpi1_title": "Afluencia Diaria Promedio",
        "kpi1_desc": "Usuarios validados por día",
        "kpi2_title": "Troncal de Mayor Demanda",
        "kpi2_desc": "Concentración de origen",
        "kpi3_title": "Hora Pico del Sistema",
        "kpi3_desc": "Período de máxima carga operativa",
        "kpi4_title": "Estación Más Concurrida",
        "kpi4_desc": "Epicentro de transacciones",
        "hero_title": "Indicadores Críticos de Rendimiento (KPIs)",
        "hero_desc": "Actualización del sistema de recaudo y operación de flota consolidada.",
        "map_title": "Mapa Interactivo de Operación",
        "map_desc": "",
        "map_box": "[ ESPACIO RESERVADO PARA MAPA FOLIUM (.geojson) ]",
        "table_title": "Métricas por Línea Troncal",
        "table_desc": "Tabla dinámica con indicadores clave de desempeño.",
        "table_box": "[ ESPACIO RESERVADO PARA DATATABLE ]",
        "th_linea": "Línea / Troncal",
        "th_estacion": "Estación Principal",
        "th_ingresos": "Validaciones Totales",
        "footer1": "TransMilenio S.A.",
        "footer2": " © 2026 — Dashboard de Visualización Analítica",
        "footer3": "Reto de Ciudades Sostenibles e Inferencia Causal",
        "btn_goto_pred": "Módulo de Inferencia Causal ➔",
        "btn_back_dash": "⬅ Retornar a Indicadores Generales",
        "pred_title": "Inferencia Causal — TransMilenio 2025",
        "pred_desc": "Efectos causales de clima, festivos, Ciclovía, eventos masivos y precio de combustible sobre la demanda del sistema.",
        "input_title": "Parámetros del Modelo",
        "output_title": "Resultado de la Predicción",
        "pred_map_title": "Mapa de Troncal: Avenida 68",
        "pred_map_desc": "Enfoque geoespacial de la ruta y proyecciones de impacto.",
        "lbl_mes": "Mes",
        "lbl_dia": "Día del Mes",
        "lbl_hora": "Hora",
        "lbl_minuto": "Minuto",
        "lbl_segundo": "Segundo",
        "lbl_zona": "Zona / Línea Troncal",
        "lbl_lat": "Latitud",
        "lbl_lon": "Longitud",
        "btn_predecir": "Ejecutar Predicción",
        "btn_limpiar": "Restablecer",
        "res_titulo": "Resultado del Modelo",
        "res_modelo": "Modelo Utilizado",
        "res_entradas": "Afluencia Estimada (Entradas)",
        "res_normalizada": "Valor Normalizado",
        "res_esperando": "Configure los parámetros y presione 'Ejecutar Predicción'",
        "res_error": "Error en la predicción",
        "metricas_titulo": "Rendimiento del Modelo",
        "metricas_rmse": "RMSE (Error Cuadrático Medio)",
        "metricas_r2": "R² (Coeficiente de Determinación)",
        # ── Tabs de inferencia causal ──
        "tab_festivos": "📅 Festivos",
        "tab_clima": "🌧️ Clima",
        "tab_ciclovia": "🚲 Ciclovía",
        "tab_campin": "🎵 Conciertos",
        "tab_combustible": "⛽ Combustible",
        "tab_simulador": "🤖 Simulador RF",
        # ── Badges de resultado ──
        "badge_confirmado": "✅ Hipótesis confirmada",
        "badge_refutado": "❌ Hipótesis refutada",
        "badge_no_confirmado": "⚠️ No confirmada",
        "badge_inconcluso": "⚠️ Inconcluso",
        # ── Contenido por análisis ──
        "festivos_titulo": "Efecto Causal de Festivos y Puentes",
        "festivos_metodo": "Event Study ±5 días  ·  R² = 0.928  ·  N = 364 días  ·  SE HC3",
        "festivos_hallazgo": "Caída promedio del −67.6% en el día del festivo. Festivos de lunes (Ley Emiliani) recuperan en 1 día; los de mitad de semana mantienen depresión 2–3 días más (diferencia +20.7 pp, p = 0.012).",
        "clima_titulo": "Efecto del Clima en la Demanda",
        "clima_metodo": "Panel FE  ·  151 estaciones × 347 días  ·  N = 49,942  ·  SE cluster-robust por estación",
        "clima_hallazgo": "La lluvia REDUCE la demanda −1.8% por cada 10mm (contrario a la hipótesis). El efecto de reducción general de movilidad supera la sustitución modal bicicleta→TM.",
        "ciclovia_titulo": "Ciclovía como Experimento Natural Recurrente",
        "ciclovia_metodo": "DiD espacial  ·  Buffer 500m en EPSG:3116  ·  63 tratadas / 86 control  ·  N = 52,385",
        "ciclovia_hallazgo": "Caída de −8.4% en domingos para estaciones cercanas, pero no significativa (p = 0.14). Identificación limitada: en 2025 todos los domingos tienen Ciclovía (sin contrafactual temporal).",
        "campin_titulo": "Impacto de Conciertos en El Campín / Movistar Arena",
        "campin_metodo": "Event Study horario  ·  7 conciertos + 8 días FdV  ·  2 estaciones primarias (245–270m)  ·  HC3",
        "campin_hallazgo": "+132% promedio en h=23 (salida del público). Bocelli: +930%. El Festival de Verano no genera el pico concentrado de los conciertos — efecto difuso por multiescenario.",
        "combustible_titulo": "Precio de Gasolina y Demanda de TransMilenio",
        "combustible_metodo": "Serie temporal mensual  ·  N = 12  ·  Niveles, log-log y primeras diferencias  ·  VIF precio↔tendencia = 6.2",
        "combustible_hallazgo": "Inconcluso por diseño: variación de precio < 2% en 2025 (N = 12) no permite separar el efecto del precio de la tendencia temporal. Requiere serie histórica 2018–2025.",
        # ── Pies de figura ──
        "fig_event_study": "Coeficientes β_k del event study con IC 95% — k = 0 es el día del festivo, k = −1 es el baseline",
        "fig_efectos_ind": "Efecto de cada festivo vs. mediana del mismo día de semana — ordenado por magnitud",
        "fig_subgrupos": "Perfiles comparados: lunes Emiliani (puente 3 días) vs. festivos de mitad de semana",
        "fig_tipo": "Efectos individuales coloreados por tipo de festivo (lunes / mitad de semana / domingo)",
        "fig_clima_fe": "Scatter precipitación vs. demanda diaria (excl. festivos) y coeficientes con IC 95%",
        "fig_clima_het": "Efectos heterogéneos del clima por línea troncal — coeficiente β con IC 95%",
        "fig_cic_mapa": "Estaciones tratadas (≤500m) y control (>500m) sobre las 15 rutas de Ciclovía IDRD",
        "fig_cic_desc": "Perfil de demanda promedio por día de semana y ratio Domingo / Día laboral",
        "fig_cic_horario": "Demanda horaria en domingos: estaciones tratadas vs. control (franja Ciclovía = 7–14h)",
        "fig_es_conc": "Coeficientes β_h del event study horario con IC 95% — efecto causal hora a hora",
        "fig_perfil_conc": "Perfil horario agregado (7 conciertos): días de evento vs. fechas de control",
        "fig_por_evento": "Perfiles individuales por concierto — ratio validaciones evento / control",
        "fig_spillover": "Efecto por franja de distancia (≤500m, 500–1500m, 1500–3000m) en horas 20h y 23h",
        "fig_vs_fdv": "Comparación conciertos individuales vs. Festival de Verano — perfil horario promedio",
        "fig_fdv_tipo": "Event study FdV desglosado: días de fin de semana vs. días hábiles",
        "fig_combustible": "Serie dual precio–demanda mensual, scatter y análisis en primeras diferencias",
    },
    "en": {
        "nav_title": "TransMilenio | Operational Monitoring & Analysis",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "kpi1_title": "Average Daily Ridership",
        "kpi1_desc": "Validated users per day",
        "kpi2_title": "Top Trunk Line",
        "kpi2_desc": "Origin concentration",
        "kpi3_title": "System Peak Hour",
        "kpi3_desc": "Maximum operational load period",
        "kpi4_title": "Busiest Station",
        "kpi4_desc": "Transaction epicenter",
        "hero_title": "Key Performance Indicators (KPIs)",
        "hero_desc": "Update on fare collection system and consolidated fleet operation.",
        "map_title": "Interactive Operational Map",
        "map_desc": "",
        "map_box": "[ RESERVED SPACE FOR FOLIUM MAP (.geojson) ]",
        "table_title": "Metrics by Trunk Line",
        "table_desc": "Dynamic table with key performance indicators.",
        "table_box": "[ RESERVED SPACE FOR DATATABLE ]",
        "th_linea": "Trunk Line",
        "th_estacion": "Main Station",
        "th_ingresos": "Total Validations",
        "footer1": "TransMilenio S.A.",
        "footer2": " © 2026 — Analytical Visualization Dashboard",
        "footer3": "Sustainable Cities & Causal Inference Challenge",
        "btn_goto_pred": "Causal Inference Module ➔",
        "btn_back_dash": "⬅ Return to General Indicators",
        "pred_title": "Causal Inference — TransMilenio 2025",
        "pred_desc": "Causal effects of weather, holidays, Ciclovía, mass events and fuel prices on transit demand.",
        "input_title": "Model Parameters",
        "output_title": "Prediction Results",
        "pred_map_title": "Trunk Map: Avenida 68",
        "pred_map_desc": "Geospatial focus of the route and impact projections.",
        "lbl_mes": "Month",
        "lbl_dia": "Day of Month",
        "lbl_hora": "Hour",
        "lbl_minuto": "Minute",
        "lbl_segundo": "Second",
        "lbl_zona": "Zone / Trunk Line",
        "lbl_lat": "Latitude",
        "lbl_lon": "Longitude",
        "btn_predecir": "Run Prediction",
        "btn_limpiar": "Reset",
        "res_titulo": "Model Result",
        "res_modelo": "Model Used",
        "res_entradas": "Estimated Ridership (Entries)",
        "res_normalizada": "Normalized Value",
        "res_esperando": "Set the parameters and press 'Run Prediction'",
        "res_error": "Prediction error",
        "metricas_titulo": "Model Performance",
        "metricas_rmse": "RMSE (Root Mean Squared Error)",
        "metricas_r2": "R² (Coefficient of Determination)",
        # ── Causal inference tabs ──
        "tab_festivos": "📅 Holidays",
        "tab_clima": "🌧️ Weather",
        "tab_ciclovia": "🚲 Ciclovía",
        "tab_campin": "🎵 Concerts",
        "tab_combustible": "⛽ Fuel",
        "tab_simulador": "🤖 RF Simulator",
        # ── Result badges ──
        "badge_confirmado": "✅ Hypothesis confirmed",
        "badge_refutado": "❌ Hypothesis refuted",
        "badge_no_confirmado": "⚠️ Not confirmed",
        "badge_inconcluso": "⚠️ Inconclusive",
        # ── Analysis content ──
        "festivos_titulo": "Causal Effect of Holidays and Long Weekends",
        "festivos_metodo": "Event Study ±5 days  ·  R² = 0.928  ·  N = 364 days  ·  HC3 SE",
        "festivos_hallazgo": "Average drop of −67.6% on the holiday day. Monday holidays (Ley Emiliani) recover in 1 day; midweek holidays sustain depression 2–3 more days (gap +20.7 pp, p = 0.012).",
        "clima_titulo": "Weather Effect on Transit Demand",
        "clima_metodo": "Panel FE  ·  151 stations × 347 days  ·  N = 49,942  ·  Cluster-robust SE by station",
        "clima_hallazgo": "Rain REDUCES demand by −1.8% per 10mm (contrary to hypothesis). General mobility reduction outweighs bicycle-to-TM modal substitution.",
        "ciclovia_titulo": "Ciclovía as a Recurring Natural Experiment",
        "ciclovia_metodo": "Spatial DiD  ·  500m buffer (EPSG:3116)  ·  63 treated / 86 control  ·  N = 52,385",
        "ciclovia_hallazgo": "−8.4% drop on Sundays for nearby stations, not significant (p = 0.14). Limited identification: all 2025 Sundays have Ciclovía — no temporal counterfactual available.",
        "campin_titulo": "Concert Impact at El Campín / Movistar Arena",
        "campin_metodo": "Hourly Event Study  ·  7 concerts + 8 FdV days  ·  2 primary stations (245–270m)  ·  HC3",
        "campin_hallazgo": "+132% average at h=23 (post-show exit). Bocelli: +930%. Summer Festival lacks the concentrated peak of individual concerts — diffuse effect across multiple venues.",
        "combustible_titulo": "Fuel Price and TransMilenio Demand",
        "combustible_metodo": "Monthly time series  ·  N = 12  ·  Levels, log-log and first differences  ·  VIF price↔trend = 6.2",
        "combustible_hallazgo": "Inconclusive by design: < 2% price variation in 2025 (N = 12) cannot separate price effect from time trend. Requires 2018–2025 historical series.",
        # ── Figure captions ──
        "fig_event_study": "Event study β_k coefficients with 95% CI — k = 0 is the holiday day, k = −1 is baseline",
        "fig_efectos_ind": "Each holiday's effect vs. same-weekday median — sorted by magnitude",
        "fig_subgrupos": "Comparison profiles: Monday Emiliani (3-day weekend) vs. midweek holidays",
        "fig_tipo": "Individual effects colored by holiday type (Monday / midweek / Sunday)",
        "fig_clima_fe": "Scatter precipitation vs. daily demand (excl. holidays) and coefficients with 95% CI",
        "fig_clima_het": "Heterogeneous weather effects by trunk line — β coefficient with 95% CI",
        "fig_cic_mapa": "Treated (≤500m) and control (>500m) stations overlaid on 15 IDRD Ciclovía routes",
        "fig_cic_desc": "Average demand profile by weekday and Sunday / Weekday ratio",
        "fig_cic_horario": "Hourly demand on Sundays: treated vs. control (Ciclovía window = 7–14h)",
        "fig_es_conc": "Hourly event study β_h coefficients with 95% CI — causal effect hour by hour",
        "fig_perfil_conc": "Aggregate hourly profile (7 concerts): event days vs. control dates",
        "fig_por_evento": "Individual profiles per concert — ratio event / control validations",
        "fig_spillover": "Effect by distance band (≤500m, 500–1500m, 1500–3000m) at hours 20h and 23h",
        "fig_vs_fdv": "Individual concerts vs. Summer Festival — average hourly profile comparison",
        "fig_fdv_tipo": "FdV event study split: weekend days vs. weekdays",
        "fig_combustible": "Dual price–demand monthly series, scatter and first-difference analysis",
    },
    "it": {
        "nav_title": "TransMilenio | Monitoraggio e Analisi Operativa",
        "theme_light": "Chiaro",
        "theme_dark": "Scuro",
        "kpi1_title": "Affluenza Media Giornaliera",
        "kpi1_desc": "Utenti validati al giorno",
        "kpi2_title": "Linea Troncale Principale",
        "kpi2_desc": "Concentrazione di origine",
        "kpi3_title": "Ora di Punta",
        "kpi3_desc": "Periodo di massimo carico operativo",
        "kpi4_title": "Stazione Più Frequentata",
        "kpi4_desc": "Epicentro delle transazioni",
        "hero_title": "Indicatori Chiave di Prestazione (KPI)",
        "hero_desc": "Aggiornamento sul sistema di esazione e operatività consolidata della flotta.",
        "map_title": "Mappa Operativa Interattiva",
        "map_desc": "",
        "map_box": "[ SPAZIO RISERVATO PER MAPPA FOLIUM (.geojson) ]",
        "table_title": "Metriche per Linea Troncale",
        "table_desc": "Tabella dinamica con indicatori chiave di prestazione.",
        "table_box": "[ SPAZIO RISERVATO PER DATATABLE ]",
        "footer1": "TransMilenio S.A.",
        "footer2": " © 2026 — Dashboard di Visualizzazione Analitica",
        "footer3": "Sfida delle Città Sostenibili e dell'Inferenza Causale",
        "btn_goto_pred": "Modulo di Inferenza Causale ➔",
        "btn_back_dash": "⬅ Ritorna agli Indicatori Generali",
        "pred_title": "Inferenza Causale — TransMilenio 2025",
        "pred_desc": "Effetti causali di clima, festività, Ciclovía, eventi di massa e prezzo del carburante sulla domanda.",
        "input_title": "Parametri del Modello",
        "output_title": "Risultati della Previsione",
        "pred_map_title": "Mappa Linea: Avenida 68",
        "pred_map_desc": "Focus geospaziale del percorso e proiezioni di impatto.",
        "lbl_mes": "Mese",
        "lbl_dia": "Giorno del Mese",
        "lbl_hora": "Ora",
        "lbl_minuto": "Minuto",
        "lbl_segundo": "Secondo",
        "lbl_zona": "Zona / Linea Troncale",
        "lbl_lat": "Latitudine",
        "lbl_lon": "Longitudine",
        "btn_predecir": "Esegui Previsione",
        "btn_limpiar": "Resetta",
        "res_titulo": "Risultato del Modello",
        "res_modelo": "Modello Utilizzato",
        "res_entradas": "Affluenza Stimata (Ingressi)",
        "res_normalizada": "Valore Normalizzato",
        "res_esperando": "Configura i parametri e premi 'Esegui Previsione'",
        "res_error": "Errore nella previsione",
        "metricas_titulo": "Prestazioni del Modello",
        "metricas_rmse": "RMSE (Errore Quadratico Medio)",
        "metricas_r2": "R² (Coefficiente di Determinazione)",
        # ── Tab di inferenza causale ──
        "tab_festivos": "📅 Festività",
        "tab_clima": "🌧️ Clima",
        "tab_ciclovia": "🚲 Ciclovía",
        "tab_campin": "🎵 Concerti",
        "tab_combustible": "⛽ Carburante",
        "tab_simulador": "🤖 Simulatore RF",
        # ── Badge risultato ──
        "badge_confirmado": "✅ Ipotesi confermata",
        "badge_refutado": "❌ Ipotesi refutata",
        "badge_no_confirmado": "⚠️ Non confermata",
        "badge_inconcluso": "⚠️ Inconcludente",
        # ── Contenuto per analisi ──
        "festivos_titulo": "Effetto Causale delle Festività e dei Ponti",
        "festivos_metodo": "Event Study ±5 giorni  ·  R² = 0.928  ·  N = 364 giorni  ·  SE HC3",
        "festivos_hallazgo": "Calo medio del −67.6% nel giorno festivo. Le festività del lunedì (Ley Emiliani) si riprendono in 1 giorno; quelle a metà settimana mantengono la depressione per 2–3 giorni in più (differenza +20.7 pp, p = 0.012).",
        "clima_titulo": "Effetto del Clima sulla Domanda di Trasporto",
        "clima_metodo": "Panel FE  ·  151 stazioni × 347 giorni  ·  N = 49.942  ·  SE cluster-robust per stazione",
        "clima_hallazgo": "La pioggia RIDUCE la domanda del −1,8% per 10mm (contrario all'ipotesi). La riduzione generale della mobilità supera la sostituzione modale bicicletta→TM.",
        "ciclovia_titulo": "Ciclovía come Esperimento Naturale Ricorrente",
        "ciclovia_metodo": "DiD spaziale  ·  Buffer 500m (EPSG:3116)  ·  63 trattate / 86 controllo  ·  N = 52.385",
        "ciclovia_hallazgo": "Calo del −8,4% nelle domeniche per le stazioni vicine, non significativo (p = 0,14). Identificazione limitata: tutte le domeniche del 2025 hanno la Ciclovía — nessun controffattuale temporale.",
        "campin_titulo": "Impatto dei Concerti all'El Campín / Movistar Arena",
        "campin_metodo": "Event Study orario  ·  7 concerti + 8 giorni FdV  ·  2 stazioni primarie (245–270m)  ·  HC3",
        "campin_hallazgo": "+132% in media alle h=23 (uscita del pubblico). Bocelli: +930%. Il Festival d'Estate non genera il picco concentrato dei concerti — effetto diffuso per multi-scenario.",
        "combustible_titulo": "Prezzo del Carburante e Domanda TransMilenio",
        "combustible_metodo": "Serie temporale mensile  ·  N = 12  ·  Livelli, log-log e prime differenze  ·  VIF prezzo↔trend = 6,2",
        "combustible_hallazgo": "Inconcludente per progettazione: variazione di prezzo < 2% nel 2025 (N = 12) non consente di separare l'effetto del prezzo dal trend temporale. Richiede serie storica 2018–2025.",
        # ── Didascalie figure ──
        "fig_event_study": "Coefficienti β_k dell'event study con IC 95% — k = 0 è il giorno festivo, k = −1 è il baseline",
        "fig_efectos_ind": "Effetto di ogni festività vs. mediana dello stesso giorno della settimana",
        "fig_subgrupos": "Confronto profili: lunedì Emiliani (ponte 3 giorni) vs. festività a metà settimana",
        "fig_tipo": "Effetti individuali colorati per tipo di festività (lunedì / metà settimana / domenica)",
        "fig_clima_fe": "Scatter precipitazione vs. domanda giornaliera (escl. festivi) e coefficienti con IC 95%",
        "fig_clima_het": "Effetti eterogenei del clima per linea troncale — coefficiente β con IC 95%",
        "fig_cic_mapa": "Stazioni trattate (≤500m) e di controllo (>500m) sulle 15 rotte Ciclovía IDRD",
        "fig_cic_desc": "Profilo medio della domanda per giorno della settimana e rapporto Dom./Lavorativo",
        "fig_cic_horario": "Domanda oraria nelle domeniche: trattate vs. controllo (finestra Ciclovía = 7–14h)",
        "fig_es_conc": "Coefficienti β_h dell'event study orario con IC 95% — effetto causale ora per ora",
        "fig_perfil_conc": "Profilo orario aggregato (7 concerti): giorni di evento vs. date di controllo",
        "fig_por_evento": "Profili individuali per concerto — rapporto validazioni evento / controllo",
        "fig_spillover": "Effetto per fascia di distanza (≤500m, 500–1500m, 1500–3000m) alle ore 20 e 23",
        "fig_vs_fdv": "Concerti individuali vs. Festival d'Estate — confronto profilo orario medio",
        "fig_fdv_tipo": "Event study FdV suddiviso: giorni di fine settimana vs. giorni lavorativi",
        "fig_combustible": "Serie doppia prezzo–domanda mensile, scatter e analisi in prime differenze",
    }
}
