# =============================================================================
# TransMilenio Dashboard — Configuración Central
# Temas, idiomas, rutas de datos y constantes institucionales.
# =============================================================================

import os

# ──── Rutas de Datos ────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(BASE_DIR))
GEOJSON_PATH = os.path.join(PROJECT_ROOT, "data", "processed", "stations_clean.geojson")

# ──── Identidad Visual Institucional ────
TM_ROJO = "#C1001F"
TM_AMARILLO = "#FFD100"
TM_TEXTO = "#333333"
TM_FONDO = "#F4F6F9"

# ──── Definición de Temas (Claro / Oscuro) ────
THEMES = {
    "light": {
        "bg_base": "#F4F6F9",
        "card_bg": "#FFFFFF",
        "text_main": "#333333",
        "text_muted": "#6C757D",
        "border": "#DEE2E6",
        "chart_box": "#F8F9FA",
        "trend_up": "text-success",
        "trend_down": "text-danger",
        "trend_warn": "text-warning",
    },
    "dark": {
        "bg_base": "#121212",
        "card_bg": "#1E1E1E",
        "text_main": "#F8F9FA",
        "text_muted": "#ADB5BD",
        "border": "#2C2C2C",
        "chart_box": "#252525",
        "trend_up": "text-success",
        "trend_down": "text-danger",
        "trend_warn": "text-warning",
    }
}

# ──── Diccionario de Traducciones (i18n) ────
LANGUAGES = {
    "es": {
        "nav_title": "TransMilenio | Monitoreo y Análisis Operativo",
        "theme_light": "Claro",
        "theme_dark": "Oscuro",
        "kpi1_title": "Afluencia Diaria Promedio",
        "kpi1_desc": "Usuarios validados por día",
        "kpi2_title": "Troncal de Mayor Demanda",
        "kpi2_desc": "Concentración de origen",
        "kpi3_title": "Hora Pico del Sistema",
        "kpi3_desc": "Período de máxima carga operativa",
        "kpi4_title": "Estación Más Concurrida",
        "kpi4_desc": "Epicentro de transacciones",
        "hero_title": "Indicadores Críticos de Rendimiento (KPIs)",
        "hero_desc": "Actualización del sistema de recaudo y operación de flota consolidada.",
        "map_title": "Mapa Interactivo de Operación",
        "map_desc": "",
        "map_box": "[ ESPACIO RESERVADO PARA MAPA FOLIUM (.geojson) ]",
        "table_title": "Métricas por Línea Troncal",
        "table_desc": "Tabla dinámica con indicadores clave de desempeño.",
        "table_box": "[ ESPACIO RESERVADO PARA DATATABLE ]",
        "th_linea": "Línea / Troncal",
        "th_estacion": "Estación Principal",
        "th_ingresos": "Validaciones Totales",
        "footer1": "TransMilenio S.A.",
        "footer2": " © 2026 — Dashboard de Visualización Analítica",
        "footer3": "Reto de Ciudades Sostenibles e Inferencia Causal",
        "btn_goto_pred": "Acceder a Módulo de Simulación Causal (Nueva Troncal) ➔",
        "btn_back_dash": "⬅ Retornar a Indicadores Generales",
        "pred_title": "Simulador de Demanda - Troncal Avenida 68",
        "pred_desc": "Proyección y modelado de afluencia basado en inferencia causal y variables operativas.",
        "input_title": "Parámetros del Modelo",
        "output_title": "Resultado de la Predicción",
        "pred_map_title": "Mapa de Troncal: Avenida 68",
        "pred_map_desc": "Enfoque geoespacial de la ruta y proyecciones de impacto.",
        "lbl_mes": "Mes",
        "lbl_dia": "Día del Mes",
        "lbl_hora": "Hora",
        "lbl_minuto": "Minuto",
        "lbl_segundo": "Segundo",
        "lbl_zona": "Zona / Línea Troncal",
        "lbl_lat": "Latitud",
        "lbl_lon": "Longitud",
        "btn_predecir": "Ejecutar Predicción",
        "btn_limpiar": "Restablecer",
        "res_titulo": "Resultado del Modelo",
        "res_modelo": "Modelo Utilizado",
        "res_entradas": "Afluencia Estimada (Entradas)",
        "res_normalizada": "Valor Normalizado",
        "res_esperando": "Configure los parámetros y presione 'Ejecutar Predicción'",
        "res_error": "Error en la predicción",
        "metricas_titulo": "Rendimiento del Modelo",
        "metricas_rmse": "RMSE (Error Cuadrático Medio)",
        "metricas_r2": "R² (Coeficiente de Determinación)",
    },
    "en": {
        "nav_title": "TransMilenio | Operational Monitoring & Analysis",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "kpi1_title": "Average Daily Ridership",
        "kpi1_desc": "Validated users per day",
        "kpi2_title": "Top Trunk Line",
        "kpi2_desc": "Origin concentration",
        "kpi3_title": "System Peak Hour",
        "kpi3_desc": "Maximum operational load period",
        "kpi4_title": "Busiest Station",
        "kpi4_desc": "Transaction epicenter",
        "hero_title": "Key Performance Indicators (KPIs)",
        "hero_desc": "Update on fare collection system and consolidated fleet operation.",
        "map_title": "Interactive Operational Map",
        "map_desc": "",
        "map_box": "[ RESERVED SPACE FOR FOLIUM MAP (.geojson) ]",
        "table_title": "Metrics by Trunk Line",
        "table_desc": "Dynamic table with key performance indicators.",
        "table_box": "[ RESERVED SPACE FOR DATATABLE ]",
        "th_linea": "Trunk Line",
        "th_estacion": "Main Station",
        "th_ingresos": "Total Validations",
        "footer1": "TransMilenio S.A.",
        "footer2": " © 2026 — Analytical Visualization Dashboard",
        "footer3": "Sustainable Cities & Causal Inference Challenge",
        "btn_goto_pred": "Access Causal Simulation Module (New Trunk Area) ➔",
        "btn_back_dash": "⬅ Return to General Indicators",
        "pred_title": "Demand Simulator - Avenida 68",
        "pred_desc": "Ridership projection and modeling based on causal inference and operational parameters.",
        "input_title": "Model Parameters",
        "output_title": "Prediction Results",
        "pred_map_title": "Trunk Map: Avenida 68",
        "pred_map_desc": "Geospatial focus of the route and impact projections.",
        "lbl_mes": "Month",
        "lbl_dia": "Day of Month",
        "lbl_hora": "Hour",
        "lbl_minuto": "Minute",
        "lbl_segundo": "Second",
        "lbl_zona": "Zone / Trunk Line",
        "lbl_lat": "Latitude",
        "lbl_lon": "Longitude",
        "btn_predecir": "Run Prediction",
        "btn_limpiar": "Reset",
        "res_titulo": "Model Result",
        "res_modelo": "Model Used",
        "res_entradas": "Estimated Ridership (Entries)",
        "res_normalizada": "Normalized Value",
        "res_esperando": "Set the parameters and press 'Run Prediction'",
        "res_error": "Prediction error",
        "metricas_titulo": "Model Performance",
        "metricas_rmse": "RMSE (Root Mean Squared Error)",
        "metricas_r2": "R² (Coefficient of Determination)",
    },
    "it": {
        "nav_title": "TransMilenio | Monitoraggio e Analisi Operativa",
        "theme_light": "Chiaro",
        "theme_dark": "Scuro",
        "kpi1_title": "Affluenza Media Giornaliera",
        "kpi1_desc": "Utenti validati al giorno",
        "kpi2_title": "Linea Troncale Principale",
        "kpi2_desc": "Concentrazione di origine",
        "kpi3_title": "Ora di Punta",
        "kpi3_desc": "Periodo di massimo carico operativo",
        "kpi4_title": "Stazione Più Frequentata",
        "kpi4_desc": "Epicentro delle transazioni",
        "hero_title": "Indicatori Chiave di Prestazione (KPI)",
        "hero_desc": "Aggiornamento sul sistema di esazione e operatività consolidata della flotta.",
        "map_title": "Mappa Operativa Interattiva",
        "map_desc": "",
        "map_box": "[ SPAZIO RISERVATO PER MAPPA FOLIUM (.geojson) ]",
        "table_title": "Metriche per Linea Troncale",
        "table_desc": "Tabella dinamica con indicatori chiave di prestazione.",
        "table_box": "[ SPAZIO RISERVATO PER DATATABLE ]",
        "footer1": "TransMilenio S.A.",
        "footer2": " © 2026 — Dashboard di Visualizzazione Analitica",
        "footer3": "Sfida delle Città Sostenibili e dell'Inferenza Causale",
        "btn_goto_pred": "Accedi al Modulo di Simulazione Causale (Nuova Linea) ➔",
        "btn_back_dash": "⬅ Ritorna agli Indicatori Generali",
        "pred_title": "Simulatore di Domanda - Avenida 68",
        "pred_desc": "Proiezione e modellizzazione dell'afflusso basata su inferenza causale e parametri operativi.",
        "input_title": "Parametri del Modello",
        "output_title": "Risultati della Previsione",
        "pred_map_title": "Mappa Linea: Avenida 68",
        "pred_map_desc": "Focus geospaziale del percorso e proiezioni di impatto.",
        "lbl_mes": "Mese",
        "lbl_dia": "Giorno del Mese",
        "lbl_hora": "Ora",
        "lbl_minuto": "Minuto",
        "lbl_segundo": "Secondo",
        "lbl_zona": "Zona / Linea Troncale",
        "lbl_lat": "Latitudine",
        "lbl_lon": "Longitudine",
        "btn_predecir": "Esegui Previsione",
        "btn_limpiar": "Resetta",
        "res_titulo": "Risultato del Modello",
        "res_modelo": "Modello Utilizzato",
        "res_entradas": "Affluenza Stimata (Ingressi)",
        "res_normalizada": "Valore Normalizzato",
        "res_esperando": "Configura i parametri e premi 'Esegui Previsione'",
        "res_error": "Errore nella previsione",
        "metricas_titulo": "Prestazioni del Modello",
        "metricas_rmse": "RMSE (Errore Quadratico Medio)",
        "metricas_r2": "R² (Coefficiente di Determinazione)",
    }
}
